-- phpMyAdmin SQL Dump
-- version 5.3.0-dev+20220618.41c48b423e
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 19, 2022 at 04:46 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `movie`
--

-- --------------------------------------------------------

--
-- Table structure for table `film`
--

CREATE TABLE `film` (
  `imdb_id` varchar(10) CHARACTER SET utf8 NOT NULL,
  `title` varchar(49) CHARACTER SET utf8 DEFAULT NULL,
  `popular_rank` int(11) DEFAULT NULL,
  `certificate` varchar(5) CHARACTER SET utf8 DEFAULT NULL,
  `startYear` int(11) DEFAULT NULL,
  `endYear` int(11) DEFAULT NULL,
  `episodes` int(11) DEFAULT NULL,
  `runtime` varchar(3) CHARACTER SET utf8 DEFAULT NULL,
  `type` varchar(12) CHARACTER SET utf8 DEFAULT NULL,
  `orign_country` varchar(14) CHARACTER SET utf8 DEFAULT NULL,
  `language` varchar(9) CHARACTER SET utf8 DEFAULT NULL,
  `plot` varchar(232) CHARACTER SET utf8 DEFAULT NULL,
  `summary` varchar(1749) CHARACTER SET utf8 DEFAULT NULL,
  `rating` decimal(2,1) DEFAULT NULL,
  `numVotes` int(11) DEFAULT NULL,
  `genres` varchar(26) CHARACTER SET utf8 DEFAULT NULL,
  `isAdult` int(11) DEFAULT NULL,
  `cast` varchar(409) CHARACTER SET utf8 DEFAULT NULL,
  `image_url` varchar(154) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `film`
--

INSERT INTO `film` (`imdb_id`, `title`, `popular_rank`, `certificate`, `startYear`, `endYear`, `episodes`, `runtime`, `type`, `orign_country`, `language`, `plot`, `summary`, `rating`, `numVotes`, `genres`, `isAdult`, `cast`, `image_url`) VALUES
('a1', 'Jurassic World: Dominion', 1, '15', 2022, NULL, NULL, '123', 'Movies', 'USA', 'english', NULL, 'Empat tahun setelah kehancuran pulau Nublar, dinosaurus sekarang hidup dan berburu bersama manusia di seluruh dunia. Keseimbangan yang rapuh ini akan menentukan, apakah manusia akan tetap menjadi berada di puncak rantai makanan ketika berbagi wilayah dengan makhluk paling menakutkan dalam sejarah bumi.\r\n', '8.3', 325654, 'action, kids, drama', 0, '[\'Chris Pratt\', \'Dadang oke\']', 'https://m.media-amazon.com/images/M/MV5BOTBjMjA4NmYtN2RjMi00YWZlLTliYTktOTIwMmNkYjYxYmE1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg'),
('a10', 'Ante Sundharaniki', 10, '13', 2022, NULL, NULL, '132', 'Movies', 'UK', 'english', 'A Hindu Brahmin falls for a Christian girl and trains her to be a Brahmin to convince his parents, only for their plan to be revealed.\r\n\r\n', 'A Hindu Brahmin falls for a Christian girl and trains her to be a Brahmin to convince his parents, only for their plan to be revealed.\r\n\r\n', '8.5', 5533, 'drama, romance', 0, '[\'Nazriya Nazim\', \'V.K. Naresh\', \'Azhagam Perumal\']', 'https://m.media-amazon.com/images/M/MV5BYTlkYmRiZDktYzJmYy00MDY4LWIxMzgtZDUxZjY3NDQ1OWEyXkEyXkFqcGdeQXVyMTA5MjQ4MDg4._V1_FMjpg_UX1000_.jpg'),
('a2', 'Top Gun: Maverick', 2, '16', 2022, NULL, NULL, '143', 'Movies', 'USA', 'english', 'After more than thirty years of service as one of the Navy\'s top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.\r\n\r\n', 'After more than thirty years of service as one of the Navy\'s top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.\r\n\r\n', '9.9', 2634, 'action, movies, drama', 0, '[\'Tom Cruise\', \'Miles Teller\']', 'https://m.media-amazon.com/images/M/MV5BMmIwZDMyYWUtNTU0ZS00ODJhLTg2ZmEtMTk5ZmYzODcxODYxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_QL75_UX190_CR0,0,190,281_.jpg'),
('a3', 'Doctor Strange in the Multiverse of Madness', 3, '12', 2022, NULL, NULL, '133', 'Movies', 'USA', 'english', 'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multi', 'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.\r\n\r\n', '8.6', 25246, 'fantasy, action, drama', 0, 'Benedict Cumberbatch, Elizabeth Olsen', 'https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_.jpg'),
('a4', 'The Bad Guys', 4, '12', 2022, NULL, NULL, '112', 'Movies', 'UK', 'english', 'Several reformed yet misunderstood criminal animals attempt to become good, with some disastrous results along the way.', 'Several reformed yet misunderstood criminal animals attempt to become good, with some disastrous results along the way.', '2.3', 425, 'kids, fantasy', 0, 'Sam Rockwell', 'https://m.media-amazon.com/images/M/MV5BMzRiYTc2MDUtNDg4ZC00NGIwLTkyNTItYTFkMGNlNGMyZGJhXkEyXkFqcGdeQXVyMTA2ODkwNzM5._V1_.jpg'),
('a5', 'The Bob\'s Burgers Movie', 5, '16', 2022, NULL, NULL, '121', 'Movies', 'USA', 'english', 'The Belchers try to save the restaurant from closing as a sinkhole forms in front of it, while the kids try to solve a mystery that could save their family\'s restaurant.', 'The Belchers try to save the restaurant from closing as a sinkhole forms in front of it, while the kids try to solve a mystery that could save their family\'s restaurant.', '3.3', 534, 'crime, action', 0, '[\'Loren bauchard\']', 'https://m.media-amazon.com/images/M/MV5BNzY3ZTdjMDktOTk1ZC00NjliLTk4MGQtN2I4N2Y4NWMyZWRmXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg'),
('a6', 'Downton Abbey: A New Era', 6, '14', 2022, NULL, NULL, '124', 'Movies', 'USA', 'english', 'Follow-up to the 2019 feature film in which the Crawley family and Downton staff received a royal visit from the King and Queen of Great Britain.\r\n\r\n', 'Follow-up to the 2019 feature film in which the Crawley family and Downton staff received a royal visit from the King and Queen of Great Britain.\r\n\r\n', '6.7', 341, 'drama, fantasy, adventure', 0, 'Hugh Boneville, Dadang Supratman', 'https://m.media-amazon.com/images/M/MV5BZDdjZjM1YWItNWRmOS00OTEzLWJmYjAtOGQzNTAyNmEwNDhjXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg'),
('a7', 'Everything Everywhere All at Once', 7, '16', 2022, NULL, NULL, '111', 'Movies', 'UK', 'english', 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.\r\n\r\n', 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.\r\n\r\n', '6.6', 53, 'action, adventure', 0, 'Michelle Yeoh, Gong xi tai kung', 'https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_FMjpg_UX1000_.jpg'),
('a8', 'Firestarter', 8, '18', 2022, NULL, NULL, '112', 'Movies', 'USA', 'english', 'A young girl tries to understand how she mysteriously gained the power to set things on fire with her mind.', 'A young girl tries to understand how she mysteriously gained the power to set things on fire with her mind.', '4.4', 425, 'drama, education', 0, 'Zac Efron, Kurniawan', 'https://m.media-amazon.com/images/M/MV5BMWIzNzA4MmUtYTIzNy00Y2Q5LWIyM2YtZGRiYzM0ZWQzOTU2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg'),
('a9', 'Sonic the Hedgehog 2', 9, '12', 2022, NULL, NULL, '111', 'Movies', 'USA', 'english', 'When the manic Dr Robotnik returns to Earth with a new ally, Knuckles the Echidna, Sonic and his new friend Tails is all that stands in their way.\r\n\r\n', 'When the manic Dr Robotnik returns to Earth with a new ally, Knuckles the Echidna, Sonic and his new friend Tails is all that stands in their way.\r\n\r\n', '8.4', 45245, 'action, adventure', 0, '[\'Jim Carrey\', \'Dadang Sudadang\']', 'https://m.media-amazon.com/images/M/MV5BNTdmNmI4MzQtZTAzNS00MjhjLWEzOGQtZjI1NDNjZjk4N2JjXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_.jpg'),
('b1', 'The Shawshank Redemption', 11, '17', 1994, NULL, NULL, '98', 'Movies', 'USA', 'english', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.\r\n\r\n', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.\r\n\r\n', '9.2', 347, 'Drama', 0, 'Tim RObbins, Tim Cook', 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg'),
('b10', 'The Good, the Bad and the Ugly', 20, '18', 1988, NULL, NULL, NULL, 'Movies', 'USA', 'english', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', '8.7', 83451, 'adventure', 0, 'Clint Eastwood', 'https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg'),
('b2', 'The Godfather', 12, '21', 1972, NULL, NULL, '128', 'Movies', 'USA', 'english', 'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.\r\n\r\n', 'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.\r\n\r\n', '9.2', 25467, 'drama, action', 0, 'Marlon Brando, Al Pacino', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('b3', 'The Dark Knight', 13, '13', 2008, NULL, NULL, '140', 'Movies', 'USA', 'english', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.\r\n\r\n', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.\r\n\r\n', '8.9', 26745, 'action, crime, drama', 0, '[\'Christian Bale\']', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg'),
('b4', 'The Godfather Part II', 14, '18', 1974, NULL, NULL, '121', 'Movies', 'USA', 'english', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.\r\n\r\n', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.\r\n\r\n', '8.7', 14444, 'action, drama', 0, 'Al Pacino, Robert De Niro', 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg'),
('b5', '12 Angry Men', 15, '18', 1957, NULL, NULL, '100', 'Movies', 'USA', 'english', 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.\r\n\r\n', 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.\r\n\r\n', '8.6', 13456, 'crime, drama', 0, '[\'Henry Fonda\', \'Lee Jacob\']', 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg'),
('b6', 'Schindler\'s List', 16, '18', 1993, NULL, NULL, '145', 'Movies', 'USA', 'english', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.\r\n\r\n', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.\r\n\r\n', '8.5', 214, 'drama', 0, 'Liam Neeson', 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('b7', 'The Lord of the Rings: The Return of the King', 17, '18', 2003, NULL, NULL, '145', 'Movies', 'USA', 'english', 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.\r\n\r\n', 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.\r\n\r\n', '8.6', 12343, 'action, adventure, drama', 0, '[\'Elijah Wood\', \'Ian Mckellen\']', 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg'),
('b8', 'Pulp Fiction', 18, '21', 1993, NULL, NULL, '123', 'Movies', 'USA', 'english', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.\r\n\r\n', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.\r\n\r\n', '8.4', 76543, 'crime, drama', 0, '[\'John Travolta\', \'Udin Penyok\']', 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('b9', 'The Lord of the Rings: The Fellowship of the Ring', 19, '13', 2001, NULL, NULL, '142', 'Movies', 'UK', 'english', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', '8.3', 7342, 'action, drama, adventure', 0, 'Elija Wood, Orlando Bloom', 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_FMjpg_UX1000_.jpg'),
('c1', 'Lucifer', 21, '15', 2016, NULL, 93, '42', 'tvSeries', 'United States', 'English', 'Lucifer Morningstar has decided he\'s had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles - the City of Angels.\r\n\r\n', 'Lucifer Morningstar has decided he\'s had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles - the City of Angels. Lucifer Morningstar has decided he\'s had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles - the City of Angels.\r\n\r\n', '8.1', 250884, 'Crime,Drama,Fantasy', 0, '[\'Tom Ellis\', \'Lauren German\']', 'https://m.media-amazon.com/images/M/MV5BNzY1YjIxOGMtOTAyZC00YTcyLWFhMzQtZTJkYTljYzU0MGRlXkEyXkFqcGdeQXVyMTAwMzM3NDI3._V1_FMjpg_UX1000_.jpg'),
('c10', 'Stranger Things', 30, '15', 2016, NULL, 34, '51', 'tvSeries', 'USA', 'engliah', 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.', 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.', '8.4', 862255, 'drama, fantasy, horror', 0, '[\'Millie Bobby Brown\', \'Finn Wolfhard\', \'Winona Ryder\', \'David Harbour\', \'Gaten Matarazzo\', \'Caleb McLaughlin\', \'Rob Morgan\']', 'https://m.media-amazon.com/images/M/MV5BN2ZmYjg1YmItNWQ4OC00YWM0LWE0ZDktYThjOTZiZjhhN2Q2XkEyXkFqcGdeQXVyNjgxNTQ3Mjk@._V1_FMjpg_UX1000_.jpg'),
('c2', 'Friends', 22, '13+', 1994, 2004, 235, '22', 'tvSeries', 'United States', 'English', 'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.', 'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan. Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.', '8.9', 861843, 'comedy,romance', 0, '[\'Jennifer Aniston\', \'Courteney Cox\']', 'https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg'),
('c3', 'NCIS: Naval Criminal Investigative Service', 23, '16', 2003, NULL, 415, '60', 'tvSeries', 'USA', 'english', 'The cases of the Naval Criminal Investigative Service\'s Washington, D.C. Major Case Response Team, led by Special Agent Leroy Jethro Gibbs.', 'The cases of the Naval Criminal Investigative Service\'s Washington, D.C. Major Case Response Team, led by Special Agent Leroy Jethro Gibbs. The cases of the Naval Criminal Investigative Service\'s Washington, D.C. Major Case Response Team, led by Special Agent Leroy Jethro Gibbs.', '7.7', 123320, 'Action,Crime,Drama', 0, '[\'Mark Harmon\', \'David McCallum\']', 'https://m.media-amazon.com/images/M/MV5BYjVlMjZhYzYtOGQxNC00OTQxLTk2NzEtMWFmMmNhODA4YjYzXkEyXkFqcGdeQXVyNjQ3MDgwNjY@._V1_FMjpg_UX1000_.jpg'),
('c4', 'Grey\'s Anatomy', 24, '15', 2005, NULL, 381, '41', 'tvSeries', 'USA', 'english', 'A drama centered on the personal and professional lives of five surgical interns and their supervisors.', 'A drama centered on the personal and professional lives of five surgical interns and their supervisors. A drama centered on the personal and professional lives of five surgical interns and their supervisors.', '7.5', 260703, 'drama, romance', 0, '[\'Ellen Pompeo\', \'Chandra Wilson\', \'James Pickens Jr.\']', 'https://m.media-amazon.com/images/M/MV5BMjgwNGNkZGYtMWQyYS00YjEzLWFmZTctODUzYWMxOWJkNTAzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg'),
('c5', 'Breaking Bad', 25, '18', 2008, 2013, 62, '49', 'tvSeries', 'USA', 'english', 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.', 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future. A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.', '9.4', 1523446, 'crime, drama, thriller', 0, '[\'Bryan Cranston\', \'Aaron Paul\', \'Anna Gunn\']', 'https://m.media-amazon.com/images/M/MV5BODFhZjAwNjEtZDFjNi00ZTEyLThkNzUtMjZmOWM2YjQwODFmXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_FMjpg_UX1000_.jpg'),
('c6', 'The Walking Dead', 26, '18', 2010, 2022, 177, '44', 'tvSeries', 'USA', 'engliah', 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.', 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive. Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.', '8.2', 873752, 'drama, horror, thriller', 0, '[\'Andrew Lincoln\', \'Norman Reedus\', \'Melissa McBride\', \'Lauren Cohan\', \'Josh McDermitt\', \'Christian Serratos\', \'Danai Gurira\']', 'https://m.media-amazon.com/images/M/MV5BMTc5ZmM0OTQtNDY4MS00ZjMyLTgwYzgtOGY0Y2VlMWFmNDU0XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_FMjpg_UX1000_.jpg'),
('c7', 'Cars', 27, '10', 2013, 2020, 93, '44', 'tvSeries', 'ireland', 'ireland', 'A hot-shot race-car named Lightning McQueen gets waylaid in Radiator Springs, where he finds the true meaning of friendship and family.', 'A hot-shot race-car named Lightning McQueen gets waylaid in Radiator Springs, where he finds the true meaning of friendship and family. A hot-shot race-car named Lightning McQueen gets waylaid in Radiator Springs, where he finds the true meaning of friendship and family.', '8.2', 45016, 'action, adventure, drama', 0, '[\'Katheryn Winnick\', \'Moe Dunford\', \'Alyssa Sutherland\', \'Linus Roache\', \'George Blagden\', \'Adam Copeland\']', 'https://m.media-amazon.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_.jpg'),
('c8', 'Peaky Blinders', 28, '15', 2013, NULL, 36, '60', 'tvSeries', 'UK', 'english', 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.', 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby. A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.', '8.4', 37802, 'crime, drama', 0, '[\'Cillian Murphy\', \'Paul Anderson\', \'Tony Pitts\', \'Aimee-Ffion Edwards\', \'Jordan Bolger\', \'Sam Neill\', \'Tom Hardy\']', 'https://m.media-amazon.com/images/M/MV5BMTkzNjEzMDEzMF5BMl5BanBnXkFtZTgwMDI0MjE4MjE@._V1_FMjpg_UX1000_.jpg'),
('c9', 'Stranger Things', 29, '15', 2016, NULL, 34, '51', 'tvSeries', 'USA', 'engliah', 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.', 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.', '8.4', 862255, 'drama, fantasy, horror', 0, '[\'Millie Bobby Brown\', \'Finn Wolfhard\', \'Winona Ryder\', \'David Harbour\', \'Gaten Matarazzo\', \'Caleb McLaughlin\', \'Rob Morgan\']', 'https://m.media-amazon.com/images/M/MV5BN2ZmYjg1YmItNWQ4OC00YWM0LWE0ZDktYThjOTZiZjhhN2Q2XkEyXkFqcGdeQXVyNjgxNTQ3Mjk@._V1_FMjpg_UX1000_.jpg'),
('d1', 'Scam 1992: The Harshad Mehta Story', 31, '17', 2020, 2021, 123, '48', 'TvSeries', 'India', 'India', 'Set in 1980s and \'90s Bombay, it follows the life of Harshad Mehta, a stockbroker who took the stock market to dizzying heights and his catastrophic downfall.\r\n\r\n', 'Set in 1980s and \'90s Bombay, it follows the life of Harshad Mehta, a stockbroker who took the stock market to dizzying heights and his catastrophic downfall. Set in 1980s and \'90s Bombay, it follows the life of Harshad Mehta, a stockbroker who took the stock market to dizzying heights and his catastrophic downfall.\r\n\r\n', '8.3', 273562, 'crime, drama', 0, '[\'Pratik Gandhi\', \'Jong Kabelesh\', \'Sharukh Khan\']', 'https://m.media-amazon.com/images/M/MV5BNjgxZTMxNmQtZGFkZS00NDUyLTllMzYtOTE0ZjdlMjM1ZWU0XkEyXkFqcGdeQXVyMTAyMTE1MDA1._V1_FMjpg_UX1000_.jpg'),
('d10', 'American Underdog', 40, '12', 2021, NULL, NULL, '123', 'Sports', 'USA', 'english', 'The story of NFL MVP and Hall of Fame quarterback Kurt Warner, who went from stocking shelves at a supermarket to becoming an American Football star.\r\n\r\n', 'The story of NFL MVP and Hall of Fame quarterback Kurt Warner, who went from stocking shelves at a supermarket to becoming an American Football star.\r\n\r\n', '9.4', 98765678, 'education, documentaries', 0, '[\'Andrew Erwin\']', 'https://m.media-amazon.com/images/M/MV5BZDUxMDdjNDItYTA2Zi00ZmJkLWIxOWQtYTk5NDlhNGYzN2ViXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_.jpg'),
('d2', 'Arcane', 32, '10', 2021, NULL, 12, '40', 'TvSeries', 'USA', 'english', 'Set in utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.\r\n\r\n', 'Set in utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart. Set in utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.\r\n\r\n', '8.3', 9358249, 'action, adventure', 0, '[\'Hailee Steinfield\', \'Jason Spisak\']', 'https://m.media-amazon.com/images/M/MV5BYmU5OWM5ZTAtNjUzOC00NmUyLTgyOWMtMjlkNjdlMDAzMzU1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UY1200_CR90,0,630,1200_AL_.jpg'),
('d3', 'The Blue Planet', 33, '8', 2001, 2004, 53, '60', 'TvSeries', 'UK', 'english', 'Mammoth series, five years in the making, taking a look at the rich tapestry of life in the world\'s oceans.\r\n\r\n', 'Mammoth series, five years in the making, taking a look at the rich tapestry of life in the world\'s oceans. Mammoth series, five years in the making, taking a look at the rich tapestry of life in the world\'s oceans.\r\n\r\n', '9.4', 999999, 'documentaries', 0, '[\'pierce Stooncan\', \'Clown Fish\']', 'https://m.media-amazon.com/images/M/MV5BMjI2NzVhM2UtODZlNS00Nzk1LTk4NDQtYTc0YWU4ODNlNGNjXkEyXkFqcGdeQXVyNjcwMzExMzU@._V1_FMjpg_UX1000_.jpg'),
('d4', 'Attack on Titan', 34, '10', 2013, 2023, 1594, '49', 'tvSeries', 'Japan', 'japananes', 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.\r\n\r\n', 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction. After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.\r\n\r\n', '8.6', 237234, 'action, adventure', 0, '[\'Josh Grelle\', \'Yuki Kaji\']', 'https://m.media-amazon.com/images/M/MV5BNzc5MTczNDQtNDFjNi00ZDU5LWFkNzItOTE1NzQzMzdhNzMxXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg'),
('d5', 'Human Planet', 35, '10', 2011, 2015, 124, '32', 'TvSeries', 'UK', 'english', 'Like all life forms, humanity partially adapts to types of natural environment, yet also tends to change them. Each episode examines how life differs for men and nature in some type of environment, from Arctic to desert and jungle, ', 'Like all life forms, humanity partially adapts to types of natural environment, yet also tends to change them. Each episode examines how life differs for men and nature in some type of environment, from Arctic to desert and jungle, from coasts to mountains. Like all life forms, humanity partially adapts to types of natural environment, yet also tends to change them. Each episode examines how life differs for men and nature in some type of environment, from Arctic to desert and jungle, from coasts to mountains.\r\n\r\n', '8.9', 83273, 'documentaries', 0, '[\'Roger Munns\', \'The People\']', 'https://m.media-amazon.com/images/M/MV5BMjdhZjQzYjYtM2FmNS00Y2ExLThjODEtZGQzY2M3OWYzYzc0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg'),
('d6', 'Home Team', 36, '10', 2022, NULL, NULL, '112', 'Sports', 'USA', 'english', 'The story about New Orleans Saints head coach Sean Payton coaching his son\'s 6th grade football team, when Payton was suspended for the entire 2012 season as a result of his role in the Saints\' Bountygate scandal.\r\n\r\n', 'The story about New Orleans Saints head coach Sean Payton coaching his son\'s 6th grade football team, when Payton was suspended for the entire 2012 season as a result of his role in the Saints\' Bountygate scandal. The story about New Orleans Saints head coach Sean Payton coaching his son\'s 6th grade football team, when Payton was suspended for the entire 2012 season as a result of his role in the Saints\' Bountygate scandal.\r\n\r\n', '8.6', 25643, 'comedy, education', 0, '[\'Kevin James\', \'Rob Schneider\']', 'https://m.media-amazon.com/images/M/MV5BYTAxMzMyZDMtMWYyYi00MTI1LThkZmUtMDYyMjc5MzU1NzljXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg'),
('d7', 'Ford v Ferrari', 37, '10', 2019, NULL, NULL, '92', 'Sports', 'USA', 'english', 'American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.\r\n\r\n', 'American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966. American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.\r\n\r\n', '8.4', 259272546, 'action, drama', 0, '[\'Matt Damon, \'Jason Keller\']', 'https://m.media-amazon.com/images/M/MV5BM2UwMDVmMDItM2I2Yi00NGZmLTk4ZTUtY2JjNTQ3OGQ5ZjM2XkEyXkFqcGdeQXVyMTA1OTYzOTUx._V1_FMjpg_UX1000_.jpg'),
('d8', 'The Blind Side', 38, '10', 2009, NULL, NULL, '120', 'Sports', 'USA', 'english', 'The story of Michael Oher, a homeless and traumatized boy who became an All-American football player and first-round NFL draft pick with the help of a caring woman and her family.\r\n\r\n', 'The story of Michael Oher, a homeless and traumatized boy who became an All-American football player and first-round NFL draft pick with the help of a caring woman and her family. The story of Michael Oher, a homeless and traumatized boy who became an All-American football player and first-round NFL draft pick with the help of a caring woman and her family.\r\n\r\n', '8.3', 98765432, 'drama', 0, '[\'Sandra Bullock\', \'Tim Andrew\']', 'https://m.media-amazon.com/images/M/MV5BMjEzOTE3ODM3OF5BMl5BanBnXkFtZTcwMzYyODI4Mg@@._V1_.jpg'),
('d9', 'The Way Back', 39, '10', 2020, NULL, NULL, '97', 'Sports', 'USA', 'english', 'Jack Cunningham was a high school basketball phenom who walked away from the game, forfeiting his future. Years later, when he reluctantly accepts a coaching job at his alma mater, he may get one last shot at redemption.\r\n\r\n', 'Jack Cunningham was a high school basketball phenom who walked away from the game, forfeiting his future. Years later, when he reluctantly accepts a coaching job at his alma mater, he may get one last shot at redemption.\r\n\r\n', '9.9', 987654321, 'action, education, documen', 0, '[\'Ben Affleck\', \'Al Madrigal\']', 'https://m.media-amazon.com/images/M/MV5BYjBjMTgyYzktN2U0Mi00YTJhLThkZDQtZmM1ZDlmNWMwZDQ3XkEyXkFqcGdeQXVyMDU5MDEyMA@@._V1_.jpg'),
('e1', 'Lightyear', 41, '15', 2022, NULL, NULL, '111', 'Kids', 'USA', 'english', 'While spending years attempting to return home, marooned Space Ranger Buzz Lightyear encounters an army of ruthless robots commanded by Zurg who are attempting to steal his fuel source.\r\n\r\n', 'While spending years attempting to return home, marooned Space Ranger Buzz Lightyear encounters an army of ruthless robots commanded by Zurg who are attempting to steal his fuel source.\r\n\r\n', '8.4', 14135, 'action, adventure, drama', 0, '[\'Romain Grosjean\']', 'https://m.media-amazon.com/images/M/MV5BYjhmNjczZTAtNGVhNy00ODliLTllYTctOTA5MDc5NWNlOWEwXkEyXkFqcGdeQXVyNDI3NjU1NzQ@._V1_.jpg'),
('e10', 'Vikings', 50, '10', 2013, 2020, 93, '44', 'tvSeries', 'ireland', 'ireland', 'Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore - and raid - the distant shores across the ocean.', 'Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore - and raid - the distant shores across the ocean. Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore - and raid - the distant shores across the ocean.', '8.2', 45016, 'action, adventure, drama', 0, '[\'Katheryn Winnick\', \'Moe Dunford\', \'Alyssa Sutherland\', \'Linus Roache\', \'George Blagden\', \'Adam Copeland\']', 'https://m.media-amazon.com/images/M/MV5BODk4ZjU0NDUtYjdlOS00OTljLTgwZTUtYjkyZjk1NzExZGIzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg'),
('e2', 'Spiderhead', 42, '20', 2022, NULL, NULL, '124', 'Movies', 'USA', 'english', 'In the near future, convicts are offered the chance to volunteer as medical subjects to shorten their sentence. One such subject for a new drug capable of generating feelings of love begins questioning the reality of his emotions.\r\n', 'In the near future, convicts are offered the chance to volunteer as medical subjects to shorten their sentence. One such subject for a new drug capable of generating feelings of love begins questioning the reality of his emotions.\r\n\r\n', '8.8', 1523, 'action, drama', 0, '[\'Michael\']', 'https://m.media-amazon.com/images/M/MV5BNDVkZTc4OTktNTAyOC00MzQxLThiZjMtM2M3MTlmYzFjY2FkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg'),
('e3', 'Brian and Charles', 43, '13', 2022, NULL, NULL, '92', 'Kids', 'USA', 'english', 'After a particularly harsh winter Brian goes into a deep depression; completely isolated and with no one to talk to, Brian does what any sane person would do when faced with such a melancholic situation. He builds a robot.\r\n\r\n', 'After a particularly harsh winter Brian goes into a deep depression; completely isolated and with no one to talk to, Brian does what any sane person would do when faced with such a melancholic situation. He builds a robot.\r\n\r\n', '2.3', 1, 'education', 0, '[\'dadang\']', 'https://m.media-amazon.com/images/M/MV5BOTA5Y2E2ODItMzk0OC00NjA0LWE3YzYtMmJkMjA1MTIxOTIzXkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_FMjpg_UX1000_.jpg'),
('e4', 'Chip \'n Dale: Rescue Rangers', 44, '10', 2022, NULL, NULL, '134', 'Kids', 'Japan', 'chinese', 'Thirty years after their popular television show ended, chipmunks Chip and Dale live very different lives. When a cast member from the original series mysteriously disappears, the pair must reunite to save their friend.\r\n\r\n', 'Thirty years after their popular television show ended, chipmunks Chip and Dale live very different lives. When a cast member from the original series mysteriously disappears, the pair must reunite to save their friend.\r\n\r\n', '8.4', 9325, 'fantasy, education', 0, '[\'Asep Kurniawan\']', 'https://m.media-amazon.com/images/M/MV5BZjBlMjIxN2ItNTMyNi00NDk5LWFhMzEtNzdiODE0Y2M4MWI2XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_FMjpg_UX1000_.jpg'),
('e5', 'Sing 2', 45, '8', 2022, NULL, NULL, NULL, 'Kids', 'USA', 'english', 'Buster Moon and his friends must persuade reclusive rock star Clay Calloway to join them for the opening of a new show.\r\n\r\n', 'Buster Moon and his friends must persuade reclusive rock star Clay Calloway to join them for the opening of a new show.\r\n\r\n', '9.2', 1234, 'comedy, drama, education', 0, '[\'Jane Ruby\']', 'https://m.media-amazon.com/images/M/MV5BOTgzYzA3NWItYzkxZC00OWQ2LTkxNTItODMyNmMxNTNkZTMxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg'),
('e6', 'Sing ', 46, '8', 2022, NULL, NULL, NULL, 'Kids', 'USA', 'english', 'Buster Moon and his friends must persuade reclusive rock star Clay Calloway to join them for the opening of a new show.\r\n\r\n', 'Buster Moon and his friends must persuade reclusive rock star Clay Calloway to join them for the opening of a new show.\r\n\r\n', '9.2', 1234, 'comedy, drama, education', 0, '[\'Jane Ruby\']', 'https://m.media-amazon.com/images/M/MV5BMTYzODYzODU2Ml5BMl5BanBnXkFtZTgwNTc1MTA2NzE@._V1_FMjpg_UX1000_.jpg'),
('e7', 'The Lord of the Rings: The Fellowship of the Ring', 47, '13', 2001, NULL, NULL, '142', 'Movies', 'UK', 'english', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', '8.3', 7342, 'action, drama, adventure', 0, 'Elija Wood, Orlando Bloom', 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_FMjpg_UX1000_.jpg'),
('e8', 'The Good, the Bad and the Ugly', 48, '18', 1988, NULL, NULL, NULL, 'Movies', 'USA', 'english', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', '8.7', 83451, 'adventure', 0, 'Clint Eastwood', 'https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg'),
('e9', 'Jurassic World', 49, '15', 2020, NULL, NULL, '123', 'Movies', 'USA', 'english', 'A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, the Indominus Rex, which escapes containment and goes on a killing spree.', 'A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, the Indominus Rex, which escapes containment and goes on a killing spree.', '8.3', 325654, 'action, kids, drama', 0, '[\'Chris Pratt\', \'Dadang oke\']', 'https://m.media-amazon.com/images/M/MV5BNzIxMjYwNDEwN15BMl5BanBnXkFtZTgwMzk5MDI3NTM@._V1_FMjpg_UX1000_.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `komentar`
--

CREATE TABLE `komentar` (
  `id` int(11) NOT NULL,
  `imdb_id` varchar(11) NOT NULL,
  `nama` varchar(30) NOT NULL,
  `komentar` text NOT NULL,
  `tanggal` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `komentar`
--

INSERT INTO `komentar` (`id`, `imdb_id`, `nama`, `komentar`, `tanggal`) VALUES
(0, 'a3', 'mkasnfs', 'SFVJAHGSYDV', '2022-06-19 12:58:53'),
(0, 'd10', 'dadangmantap', 'keren eeuuuyyyy', '2022-06-19 14:46:20');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `film`
--
ALTER TABLE `film`
  ADD PRIMARY KEY (`imdb_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;



